# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-a21fac4b-9986-4ec4-a233-929f60ebfa0e";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."luks-a21fac4b-9986-4ec4-a233-929f60ebfa0e".device = "/dev/disk/by-uuid/a21fac4b-9986-4ec4-a233-929f60ebfa0e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0489-41C8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-1c9181b1-f574-4464-84f5-383abd1f2c51"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
