backend = "egl";
vsync = false;
use-damage = false;

shadow = true;
shadow-radius = 20;
shadow-opacity = 0.6;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-exclude = [
  "window_type = 'desktop'",
  "_NET_WM_STATE *= '_NET_WM_STATE_HIDDEN'",
  "class_g = 'cs2' && fullscreen",
  "class_g = 'steam_app_730' && fullscreen"
];

fading = true;
no-fading-openclose = true;
fade-delta = 6;
fade-exclude = [
  "window_type = 'desktop'",
  "class_g = 'cs2' && fullscreen",
  "class_g = 'steam_app_730' && fullscreen"
];

unredir-if-possible = false;
no-ewmh-fullscreen = true;

wintypes = {
  desktop = { shadow = false; fade = false; blur-background = false; };
};

blur-background-exclude = [
  "window_type = 'desktop'",
  "class_g = 'cs2' && fullscreen",
  "class_g = 'steam_app_730' && fullscreen"
];

blur = {
  method = "dual_kawase";
  strength = 6;
};

opacity-rule = [
  "100:class_g = 'cs2' && fullscreen",
  "100:class_g = 'steam_app_730' && fullscreen",
  "90:class_g = 'Alacritty'",
  "85:class_g = 'Rofi'"
];

blur-background = true;
blur-background-frame = true;
blur-background-fixed = true;

# active-opacity = 0.77;
# inactive-opacity = 0.90;
# frame-opacity = 1.00;
